import { Header } from "@/components/shared/Header";
import "./globals.css";
import type { Metadata } from "next";
import { roboto } from "./fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Trying to make sure the screen doesn't zoom in.
export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: "0",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${roboto.variable}`}>
        <Header />
        <div className="mt-32 md:mt-[4.7rem]">{children}</div>
      </body>
    </html>
  );
}
